





<div id="g-20231231_imagenGuitarraApertura-box" class="ai2html">
	<!-- Generated by ai2html v0.65.2 - 2023-12-31 - 00:58 -->
	<!-- ai file: 2023xxxx_Imagen guitarra apertura.ai -->

	<style type='text/css' media='screen,print'>
		#g-20231231_imagenGuitarraApertura-box .g-artboard {
			margin:0 auto;
		}
		#g-20231231_imagenGuitarraApertura-box .g-artboard p {
			margin:0;
		}
		.g-aiAbs {
			position:absolute;
		}
		.g-aiImg {
			display:block;
			width:100% !important;
		}
		.g-aiPointText p { white-space: nowrap; }
	</style>

	<style type='text/css' media='screen,print'>
		/* Custom CSS */
				#g-20231231_imagenGuitarraApertura-movil {
			display:block;
			max-width: 300px !important;
		}
		#g-20231231_imagenGuitarraApertura-escritorio1200,
		#g-20231231_imagenGuitarraApertura-escritorio,
		#g-20231231_imagenGuitarraApertura-tableta,
		#g-20231231_imagenGuitarraApertura-movil2{ 
			display:none;
			}
		@media (min-width:375px) {
			#g-20231231_imagenGuitarraApertura-movil{
				display: none;
			}
			#g-20231231_imagenGuitarraApertura-movil2{
				display:block;
				width: 100% !important;
			}
		}
		@media (min-width:414px) {
			#g-20231231_imagenGuitarraApertura-movil{
				display: none;
			}
			#g-20231231_imagenGuitarraApertura-movil2{
				display:block;
				max-width: 375px !important;
			}
		}
		@media (min-width:566px) {
			#g-20231231_imagenGuitarraApertura-movil2{
				display: none;
			}
			#g-20231231_imagenGuitarraApertura-tableta{
				display:block;
			}
		}
		@media (min-width:833px) {
			#g-20231231_imagenGuitarraApertura-tableta{
				display: none;
			}
			#g-20231231_imagenGuitarraApertura-escritorio{
				display:block;
			}
		}
		@media (min-width:1200px) {
			#g-20231231_imagenGuitarraApertura-escritorio{
				display: none;
			}
			#g-20231231_imagenGuitarraApertura-escritorio1200{
				display:block;	
			}
			#g-20231231_imagenGuitarraApertura-box {
				margin-left: 0;
				margin-right: 0;
			}
		} 
	</style>

	<!-- Artboard: movil -->
	<div id="g-20231231_imagenGuitarraApertura-movil" class="g-artboard g-artboard-v3" data-min-width='289' data-max-width='344'>
		<style type='text/css' media='screen,print'>
			#g-20231231_imagenGuitarraApertura-movil {
				position:relative;
				overflow:hidden;
				width:289px;
			}
		</style>
		<img id="g-ai0-0" class="g-aiImg" src="https://visuals.lavanguardia.com/ai2html/20231231_imagenGuitarraApertura/20231231_imagenGuitarraApertura-movil.jpg"/>
	</div>

	<!-- Artboard: movil2 -->
	<div id="g-20231231_imagenGuitarraApertura-movil2" class="g-artboard g-artboard-v3" data-min-width='345' data-max-width='565'>
		<style type='text/css' media='screen,print'>
			#g-20231231_imagenGuitarraApertura-movil2 {
				position:relative;
				overflow:hidden;
				width:345px;
			}
		</style>
		<img id="g-ai1-0" class="g-aiImg" src="https://visuals.lavanguardia.com/ai2html/20231231_imagenGuitarraApertura/20231231_imagenGuitarraApertura-movil2.jpg"/>
	</div>

	<!-- Artboard: tableta -->
	<div id="g-20231231_imagenGuitarraApertura-tableta" class="g-artboard g-artboard-v3" data-min-width='566' data-max-width='832'>
		<style type='text/css' media='screen,print'>
			#g-20231231_imagenGuitarraApertura-tableta {
				position:relative;
				overflow:hidden;
				width:566px;
			}
		</style>
		<img id="g-ai2-0" class="g-aiImg" src="https://visuals.lavanguardia.com/ai2html/20231231_imagenGuitarraApertura/20231231_imagenGuitarraApertura-tableta.jpg"/>
	</div>

	<!-- Artboard: escritorio -->
	<div id="g-20231231_imagenGuitarraApertura-escritorio" class="g-artboard g-artboard-v3" data-min-width='833' data-max-width='1199'>
		<style type='text/css' media='screen,print'>
			#g-20231231_imagenGuitarraApertura-escritorio {
				position:relative;
				overflow:hidden;
				width:833px;
			}
		</style>
		<img id="g-ai3-0" class="g-aiImg" src="https://visuals.lavanguardia.com/ai2html/20231231_imagenGuitarraApertura/20231231_imagenGuitarraApertura-escritorio.jpg"/>
	</div>

	<!-- Artboard: escritorio1200 -->
	<div id="g-20231231_imagenGuitarraApertura-escritorio1200" class="g-artboard g-artboard-v3" data-min-width='1200'>
		<style type='text/css' media='screen,print'>
			#g-20231231_imagenGuitarraApertura-escritorio1200 {
				position:relative;
				overflow:hidden;
				width:1200px;
			}
		</style>
		<img id="g-ai4-0" class="g-aiImg" src="https://visuals.lavanguardia.com/ai2html/20231231_imagenGuitarraApertura/20231231_imagenGuitarraApertura-escritorio1200.jpg"/>
	</div>
	<!-- End ai2html - 2023-12-31 - 00:58 -->
</div>
