
<div id="g-20231231_sonidoGuitarra-box" class="ai2html">
	<!-- Generated by ai2html v0.65.2 - 2023-12-31 - 00:18 -->
	<!-- ai file: 2023xxxx_SonidoGuitarra.ai -->

	<style type='text/css' media='screen,print'>
		#g-20231231_sonidoGuitarra-box .g-artboard {
			margin:0 auto;
		}
		#g-20231231_sonidoGuitarra-box .g-artboard p {
			margin:0;
		}
		.g-aiAbs {
			position:absolute;
		}
		.g-aiImg {
			display:block;
			width:100% !important;
		}
		.g-aiPointText p { white-space: nowrap; }
	</style>

	<style type='text/css' media='screen,print'>
		/* Custom CSS */
				#g-20231231_sonidoGuitarra-movil {
			display:block;
			max-width: 300px !important;
		}
		#g-20231231_sonidoGuitarra-escritorio1200,
		#g-20231231_sonidoGuitarra-escritorio,
		#g-20231231_sonidoGuitarra-tableta,
		#g-20231231_sonidoGuitarra-movil2{ 
			display:none;
			}
		@media (min-width:375px) {
			#g-20231231_sonidoGuitarra-movil{
				display: none;
			}
			#g-20231231_sonidoGuitarra-movil2{
				display:block;
				width: 100% !important;
			}
		}
		@media (min-width:414px) {
			#g-20231231_sonidoGuitarra-movil{
				display: none;
			}
			#g-20231231_sonidoGuitarra-movil2{
				display:block;
				max-width: 375px !important;
			}
		}
		@media (min-width:566px) {
			#g-20231231_sonidoGuitarra-movil2{
				display: none;
			}
			#g-20231231_sonidoGuitarra-tableta{
				display:block;
			}
		}
		@media (min-width:833px) {
			#g-20231231_sonidoGuitarra-tableta{
				display: none;
			}
			#g-20231231_sonidoGuitarra-escritorio{
				display:block;
			}
		}
		@media (min-width:1200px) {
			#g-20231231_sonidoGuitarra-escritorio{
				display: none;
			}
			#g-20231231_sonidoGuitarra-escritorio1200{
				display:block;	
			}
			#g-20231231_sonidoGuitarra-box {
				margin-left: 0;
				margin-right: 0;
			}
		} 
	</style>

	<!-- Artboard: movil -->
	<div id="g-20231231_sonidoGuitarra-movil" class="g-artboard g-artboard-v3" data-min-width='289' data-max-width='344'>
		<style type='text/css' media='screen,print'>
			#g-20231231_sonidoGuitarra-movil {
				position:relative;
				overflow:hidden;
				width:289px;
			}
			#g-20231231_sonidoGuitarra-movil p {
				font-family:Roboto,sans-serif;
				font-weight:400;
				font-size:12px;
				line-height:15px;
				filter:alpha(opacity=100);
				-ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
				opacity:1;
				letter-spacing:0em;
				text-align:left;
				color:rgb(0,0,0);
				text-transform:none;
				padding-bottom:0;
				padding-top:0;
				mix-blend-mode:normal;
				font-style:normal;
			}
			#g-20231231_sonidoGuitarra-movil .g-pstyle0 {
				font-weight:700;
				font-size:16px;
				line-height:20px;
			}
			#g-20231231_sonidoGuitarra-movil .g-pstyle1 {
				font-weight:700;
			}
			#g-20231231_sonidoGuitarra-movil .g-pstyle2 {
				color:rgb(242,242,242);
			}
			#g-20231231_sonidoGuitarra-movil .g-cstyle0 {
				color:rgb(240,182,70);
			}
		</style>
		<img id="g-ai0-0" class="g-aiImg" src="https://visuals.lavanguardia.com/ai2html/20231231_sonidoGuitarra/20231231_sonidoGuitarra-movil.jpg"/>
		<div id="g-ai0-1" class="g-ai2html-settings g-aiAbs" style="top:7.1895%;left:0.9204%;width:73.3564%;">
			<p class="g-pstyle0">Cómo se genera el <span class="g-cstyle0">sonido</span></p>
		</div>
		<div id="g-ai0-2" class="g-ai2html-settings g-aiAbs" style="top:11.2977%;left:0.9204%;width:70.2422%;">
			<p>El sonido de una guitarra se genera a través de la vibración de las cuerdas al ser pulsadas. La caja de resonancia y sus materiales son los encargados de amplificar y matizar el sonido</p>
		</div>
		<div id="g-ai0-3" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:30.2019%;margin-top:-8.2px;left:0.6126%;width:12px;">
			<p class="g-pstyle1">1.</p>
		</div>
		<div id="g-ai0-4" class="g-ai2html-settings g-aiAbs" style="top:29.143%;left:5.7568%;width:54.3253%;">
			<p>Al tocar (pulsar) las cuerdas, entran en movimiento</p>
		</div>
		<div id="g-ai0-5" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:37.263%;margin-top:-8.2px;left:0.6235%;width:12px;">
			<p class="g-pstyle1">2.</p>
		</div>
		<div id="g-ai0-6" class="g-ai2html-settings g-aiAbs" style="top:36.2041%;left:5.7677%;width:35.2941%;">
			<p>Esas vibraciones se transmiten a través del puente, a la tapa armónica</p>
		</div>
		<div id="g-ai0-7" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:48.3039%;margin-top:-8.2px;left:44.8889%;width:29px;">
			<p class="g-pstyle2">Boca</p>
		</div>
		<div id="g-ai0-8" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:48.6891%;margin-top:-8.2px;left:66.3479%;width:12px;">
			<p class="g-pstyle1">4.</p>
		</div>
		<div id="g-ai0-9" class="g-ai2html-settings g-aiAbs" style="top:47.6302%;left:71.492%;width:29.4118%;">
			<p>El sonido sale por la boca de la caja</p>
		</div>
		<div id="g-ai0-10" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:81.6836%;margin-top:-8.2px;left:58.8162%;width:36px;">
			<p class="g-pstyle2">Fondo</p>
		</div>
		<div id="g-ai0-11" class="g-ai2html-settings g-aiAbs" style="top:90.5102%;left:52.5103%;width:49.1349%;">
			<p>La caja de resonancia amplifica y matiza el sonido gracias al varetaje</p>
		</div>
		<div id="g-ai0-12" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:91.5691%;margin-top:-8.2px;left:47.3663%;width:12px;">
			<p class="g-pstyle1">3.</p>
		</div>
	</div>

	<!-- Artboard: movil2 -->
	<div id="g-20231231_sonidoGuitarra-movil2" class="g-artboard g-artboard-v3" data-min-width='345' data-max-width='565'>
		<style type='text/css' media='screen,print'>
			#g-20231231_sonidoGuitarra-movil2 {
				position:relative;
				overflow:hidden;
				width:345px;
			}
			#g-20231231_sonidoGuitarra-movil2 p {
				font-family:Roboto,sans-serif;
				font-weight:400;
				font-size:14px;
				line-height:17px;
				filter:alpha(opacity=100);
				-ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
				opacity:1;
				letter-spacing:0em;
				text-align:left;
				color:rgb(0,0,0);
				text-transform:none;
				padding-bottom:0;
				padding-top:0;
				mix-blend-mode:normal;
				font-style:normal;
			}
			#g-20231231_sonidoGuitarra-movil2 .g-pstyle0 {
				font-weight:700;
				font-size:19px;
				line-height:23px;
			}
			#g-20231231_sonidoGuitarra-movil2 .g-pstyle1 {
				font-weight:700;
			}
			#g-20231231_sonidoGuitarra-movil2 .g-pstyle2 {
				color:rgb(242,242,242);
			}
			#g-20231231_sonidoGuitarra-movil2 .g-cstyle0 {
				color:rgb(240,182,70);
			}
		</style>
		<img id="g-ai1-0" class="g-aiImg" src="https://visuals.lavanguardia.com/ai2html/20231231_sonidoGuitarra/20231231_sonidoGuitarra-movil2.jpg"/>
		<div id="g-ai1-1" class="g-ai2html-settings g-aiAbs" style="top:5.9978%;left:1.3102%;width:71.8841%;">
			<p class="g-pstyle0">Cómo se genera el <span class="g-cstyle0">sonido</span></p>
		</div>
		<div id="g-ai1-2" class="g-ai2html-settings g-aiAbs" style="top:10.1075%;left:1.3102%;width:68.6957%;">
			<p>El sonido de una guitarra se genera a través de la vibración de las cuerdas al ser pulsadas. La caja de resonancia y sus materiales son los encargados de amplificar y matizar el sonido</p>
		</div>
		<div id="g-ai1-3" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:29.2545%;margin-top:-9.4px;left:1.0091%;width:14px;">
			<p class="g-pstyle1">1.</p>
		</div>
		<div id="g-ai1-4" class="g-ai2html-settings g-aiAbs" style="top:28.2121%;left:6.0445%;width:53.3333%;">
			<p>Al tocar (pulsar) las cuerdas, entran en movimiento</p>
		</div>
		<div id="g-ai1-5" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:36.3631%;margin-top:-9.4px;left:1.0197%;width:14px;">
			<p class="g-pstyle1">2.</p>
		</div>
		<div id="g-ai1-6" class="g-ai2html-settings g-aiAbs" style="top:35.3207%;left:6.0552%;width:34.4928%;">
			<p>Esas vibraciones se transmiten a través del puente, a la tapa armónica</p>
		</div>
		<div id="g-ai1-7" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:47.4702%;margin-top:-9.4px;left:44.3506%;width:34px;">
			<p class="g-pstyle2">Boca</p>
		</div>
		<div id="g-ai1-8" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:48.0256%;margin-top:-9.4px;left:65.3566%;width:14px;">
			<p class="g-pstyle1">4.</p>
		</div>
		<div id="g-ai1-9" class="g-ai2html-settings g-aiAbs" style="top:46.9831%;left:70.3922%;width:28.9855%;">
			<p>El sonido sale por la boca de la caja</p>
		</div>
		<div id="g-ai1-10" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:81.347%;margin-top:-9.4px;left:57.9841%;width:41px;">
			<p class="g-pstyle2">Fondo</p>
		</div>
		<div id="g-ai1-11" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:91.3434%;margin-top:-9.4px;left:46.7756%;width:14px;">
			<p class="g-pstyle1">3.</p>
		</div>
		<div id="g-ai1-12" class="g-ai2html-settings g-aiAbs" style="top:90.3009%;left:51.8112%;width:48.1159%;">
			<p>La caja de resonancia amplifica y matiza el sonido gracias al varetaje</p>
		</div>
	</div>

	<!-- Artboard: tableta -->
	<div id="g-20231231_sonidoGuitarra-tableta" class="g-artboard g-artboard-v3" data-min-width='566' data-max-width='832'>
		<style type='text/css' media='screen,print'>
			#g-20231231_sonidoGuitarra-tableta {
				position:relative;
				overflow:hidden;
				width:566px;
			}
			#g-20231231_sonidoGuitarra-tableta p {
				font-family:Roboto,sans-serif;
				font-weight:400;
				font-size:14px;
				line-height:17px;
				filter:alpha(opacity=100);
				-ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
				opacity:1;
				letter-spacing:0em;
				text-align:left;
				color:rgb(0,0,0);
				text-transform:none;
				padding-bottom:0;
				padding-top:0;
				mix-blend-mode:normal;
				font-style:normal;
			}
			#g-20231231_sonidoGuitarra-tableta .g-pstyle0 {
				font-weight:700;
				font-size:19px;
				line-height:23px;
			}
			#g-20231231_sonidoGuitarra-tableta .g-pstyle1 {
				font-weight:700;
			}
			#g-20231231_sonidoGuitarra-tableta .g-pstyle2 {
				color:rgb(242,242,242);
			}
			#g-20231231_sonidoGuitarra-tableta .g-cstyle0 {
				color:rgb(240,182,70);
			}
		</style>
		<img id="g-ai2-0" class="g-aiImg" src="https://visuals.lavanguardia.com/ai2html/20231231_sonidoGuitarra/20231231_sonidoGuitarra-tableta.jpg"/>
		<div id="g-ai2-1" class="g-ai2html-settings g-aiAbs" style="top:3.2763%;left:51.4932%;width:43.8163%;">
			<p class="g-pstyle0">Cómo se genera el <span class="g-cstyle0">sonido</span></p>
		</div>
		<div id="g-ai2-2" class="g-ai2html-settings g-aiAbs" style="top:7.0646%;left:51.4932%;width:42.0495%;">
			<p>El sonido de una guitarra se genera a través de la vibración de las cuerdas al ser pulsadas. La caja de resonancia y sus materiales son los encargados de amplificar y matizar el sonido</p>
		</div>
		<div id="g-ai2-3" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:21.5403%;margin-top:-9.4px;left:51.1329%;width:14px;">
			<p class="g-pstyle1">1.</p>
		</div>
		<div id="g-ai2-4" class="g-ai2html-settings g-aiAbs" style="top:20.5794%;left:54.2023%;width:21.3781%;">
			<p>Al tocar (pulsar) las cuerdas, entran en movimiento</p>
		</div>
		<div id="g-ai2-5" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:30.4478%;margin-top:-9.4px;left:59.2601%;width:14px;">
			<p class="g-pstyle1">4.</p>
		</div>
		<div id="g-ai2-6" class="g-ai2html-settings g-aiAbs" style="top:29.4869%;left:62.3295%;width:15.5477%;">
			<p>El sonido sale por la boca de la caja</p>
		</div>
		<div id="g-ai2-7" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:39.7648%;margin-top:-9.4px;left:25.1678%;width:14px;">
			<p class="g-pstyle1">2.</p>
		</div>
		<div id="g-ai2-8" class="g-ai2html-settings g-aiAbs" style="top:38.8039%;left:28.2371%;width:21.0247%;">
			<p>Esas vibraciones se transmiten a través del puente, a la tapa armónica</p>
		</div>
		<div id="g-ai2-9" class="g-ai2html-settings g-aiAbs" style="top:38.8039%;left:0.7241%;width:21.7314%;">
			<p>La tapa armónica suele construirse en cedro o abeto, con las vetas de la madera en la misma dirección que las cuerdas...</p>
		</div>
		<div id="g-ai2-10" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:50.0033%;margin-top:-9.4px;left:60.9446%;width:34px;">
			<p class="g-pstyle2">Boca</p>
		</div>
		<div id="g-ai2-11" class="g-ai2html-settings g-aiAbs" style="top:55.1855%;left:0.7241%;width:20.318%;">
			<p>...ya que las vibraciones se transmiten mejor y con un mayor recorrido a lo largo de la veta</p>
		</div>
		<div id="g-ai2-12" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:84.507%;margin-top:-9.4px;left:0.5178%;width:42px;">
			<p>Culata</p>
		</div>
		<div id="g-ai2-13" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:85.3261%;margin-top:-9.4px;left:79.8528%;width:14px;">
			<p class="g-pstyle1">3.</p>
		</div>
		<div id="g-ai2-14" class="g-ai2html-settings g-aiAbs" style="top:84.3652%;left:82.9223%;width:16.9611%;">
			<p>La caja de resonancia amplifica y matiza el sonido gracias al varetaje</p>
		</div>
		<div id="g-ai2-15" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:89.6262%;margin-top:-9.4px;left:50.0561%;width:41px;">
			<p class="g-pstyle2">Fondo</p>
		</div>
	</div>

	<!-- Artboard: escritorio -->
	<div id="g-20231231_sonidoGuitarra-escritorio" class="g-artboard g-artboard-v3" data-min-width='833' data-max-width='1199'>
		<style type='text/css' media='screen,print'>
			#g-20231231_sonidoGuitarra-escritorio {
				position:relative;
				overflow:hidden;
				width:833px;
			}
			#g-20231231_sonidoGuitarra-escritorio p {
				font-family:Roboto,sans-serif;
				font-weight:400;
				font-size:14px;
				line-height:17px;
				filter:alpha(opacity=100);
				-ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
				opacity:1;
				letter-spacing:0em;
				text-align:left;
				color:rgb(0,0,0);
				text-transform:none;
				padding-bottom:0;
				padding-top:0;
				mix-blend-mode:normal;
				font-style:normal;
			}
			#g-20231231_sonidoGuitarra-escritorio .g-pstyle0 {
				font-weight:700;
				font-size:19px;
				line-height:23px;
			}
			#g-20231231_sonidoGuitarra-escritorio .g-pstyle1 {
				font-weight:700;
			}
			#g-20231231_sonidoGuitarra-escritorio .g-pstyle2 {
				color:rgb(242,242,242);
			}
			#g-20231231_sonidoGuitarra-escritorio .g-cstyle0 {
				color:rgb(240,182,70);
			}
		</style>
		<img id="g-ai3-0" class="g-aiImg" src="https://visuals.lavanguardia.com/ai2html/20231231_sonidoGuitarra/20231231_sonidoGuitarra-escritorio.jpg"/>
		<div id="g-ai3-1" class="g-ai2html-settings g-aiAbs" style="top:3.5321%;left:51.4778%;width:29.7719%;">
			<p class="g-pstyle0">Cómo se genera el <span class="g-cstyle0">sonido</span></p>
		</div>
		<div id="g-ai3-2" class="g-ai2html-settings g-aiAbs" style="top:6.8876%;left:51.4778%;width:28.5714%;">
			<p>El sonido de una guitarra se genera a través de la vibración de las cuerdas al ser pulsadas. La caja de resonancia y sus materiales son los encargados de amplificar y matizar el sonido</p>
		</div>
		<div id="g-ai3-3" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:19.9903%;margin-top:-9.4px;left:51.233%;width:14px;">
			<p class="g-pstyle1">1.</p>
		</div>
		<div id="g-ai3-4" class="g-ai2html-settings g-aiAbs" style="top:19.1616%;left:53.3185%;width:14.5258%;">
			<p>Al tocar (pulsar) las cuerdas, entran en movimiento</p>
		</div>
		<div id="g-ai3-5" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:28.2024%;margin-top:-9.4px;left:62.3574%;width:14px;">
			<p class="g-pstyle1">4.</p>
		</div>
		<div id="g-ai3-6" class="g-ai2html-settings g-aiAbs" style="top:27.3736%;left:64.4429%;width:10.5642%;">
			<p>El sonido sale por la boca de la caja</p>
		</div>
		<div id="g-ai3-7" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:35.0899%;margin-top:-9.4px;left:26.4675%;width:14px;">
			<p class="g-pstyle1">2.</p>
		</div>
		<div id="g-ai3-8" class="g-ai2html-settings g-aiAbs" style="top:34.2612%;left:28.5531%;width:14.2857%;">
			<p>Esas vibraciones se transmiten a través del puente, a la tapa armónica</p>
		</div>
		<div id="g-ai3-9" class="g-ai2html-settings g-aiAbs" style="top:34.2612%;left:1.3754%;width:14.7659%;">
			<p>La tapa armónica suele construirse en cedro o abeto, con las vetas de la madera en la misma dirección que las cuerdas...</p>
		</div>
		<div id="g-ai3-10" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:43.8318%;margin-top:-9.4px;left:63.7761%;width:34px;">
			<p class="g-pstyle2">Boca</p>
		</div>
		<div id="g-ai3-11" class="g-ai2html-settings g-aiAbs" style="top:48.3012%;left:1.3754%;width:13.8055%;">
			<p>...ya que las vibraciones se transmiten mejor y con un mayor recorrido a lo largo de la veta</p>
		</div>
		<div id="g-ai3-12" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:53.6334%;margin-top:-9.4px;left:31.2125%;width:44px;">
			<p>Selleta</p>
		</div>
		<div id="g-ai3-13" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:65.2893%;margin-top:-9.4px;left:40.9352%;width:46px;">
			<p class="g-pstyle2">Puente</p>
		</div>
		<div id="g-ai3-14" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:75.6206%;margin-top:-9.4px;left:76.9099%;width:14px;">
			<p class="g-pstyle1">3.</p>
		</div>
		<div id="g-ai3-15" class="g-ai2html-settings g-aiAbs" style="top:74.7919%;left:78.9954%;width:19.6879%;">
			<p>La caja de resonancia amplifica y matiza el sonido gracias al varetaje</p>
		</div>
		<div id="g-ai3-16" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:78.6229%;margin-top:-9.4px;left:0.8707%;width:42px;">
			<p>Culata</p>
		</div>
		<div id="g-ai3-17" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:88.5127%;margin-top:-9.4px;left:44.3435%;width:41px;">
			<p class="g-pstyle2">Fondo</p>
		</div>
	</div>

	<!-- Artboard: escritorio1200 -->
	<div id="g-20231231_sonidoGuitarra-escritorio1200" class="g-artboard g-artboard-v3" data-min-width='1200'>
		<style type='text/css' media='screen,print'>
			#g-20231231_sonidoGuitarra-escritorio1200 {
				position:relative;
				overflow:hidden;
				width:1200px;
			}
			#g-20231231_sonidoGuitarra-escritorio1200 p {
				font-family:Roboto,sans-serif;
				font-weight:400;
				font-size:14px;
				line-height:17px;
				filter:alpha(opacity=100);
				-ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
				opacity:1;
				letter-spacing:0em;
				text-align:left;
				color:rgb(0,0,0);
				text-transform:none;
				padding-bottom:0;
				padding-top:0;
				mix-blend-mode:normal;
				font-style:normal;
			}
			#g-20231231_sonidoGuitarra-escritorio1200 .g-pstyle0 {
				font-weight:700;
				font-size:19px;
				line-height:23px;
			}
			#g-20231231_sonidoGuitarra-escritorio1200 .g-pstyle1 {
				font-weight:700;
			}
			#g-20231231_sonidoGuitarra-escritorio1200 .g-pstyle2 {
				color:rgb(242,242,242);
			}
			#g-20231231_sonidoGuitarra-escritorio1200 .g-cstyle0 {
				color:rgb(240,182,70);
			}
		</style>
		<img id="g-ai4-0" class="g-aiImg" src="https://visuals.lavanguardia.com/ai2html/20231231_sonidoGuitarra/20231231_sonidoGuitarra-escritorio1200.jpg"/>
		<div id="g-ai4-1" class="g-ai2html-settings g-aiAbs" style="top:5.526%;left:50.7523%;width:20.6667%;">
			<p class="g-pstyle0">Cómo se genera el <span class="g-cstyle0">sonido</span></p>
		</div>
		<div id="g-ai4-2" class="g-ai2html-settings g-aiAbs" style="top:8.6239%;left:50.7523%;width:19.8333%;">
			<p>El sonido de una guitarra se genera a través de la vibración de las cuerdas al ser pulsadas. La caja de resonancia y sus materiales son los encargados de amplificar y matizar el sonido</p>
		</div>
		<div id="g-ai4-3" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:24.5644%;margin-top:-9.4px;left:39.1657%;width:14px;">
			<p class="g-pstyle1">1.</p>
		</div>
		<div id="g-ai4-4" class="g-ai2html-settings g-aiAbs" style="top:23.7786%;left:40.6134%;width:10.0833%;">
			<p>Al tocar (pulsar) las cuerdas, entran en movimiento</p>
		</div>
		<div id="g-ai4-5" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:32.2673%;margin-top:-9.4px;left:43.5546%;width:14px;">
			<p class="g-pstyle1">4.</p>
		</div>
		<div id="g-ai4-6" class="g-ai2html-settings g-aiAbs" style="top:31.4815%;left:45.0023%;width:7.3333%;">
			<p>El sonido sale por la boca de la caja</p>
		</div>
		<div id="g-ai4-7" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:38.798%;margin-top:-9.4px;left:18.6411%;width:14px;">
			<p class="g-pstyle1">2.</p>
		</div>
		<div id="g-ai4-8" class="g-ai2html-settings g-aiAbs" style="top:38.0122%;left:20.0888%;width:9.9167%;">
			<p>Esas vibraciones se transmiten a través del puente, a la tapa armónica</p>
		</div>
		<div id="g-ai4-9" class="g-ai2html-settings g-aiAbs" style="top:38.0122%;left:1.2229%;width:10.25%;">
			<p>La tapa armónica suele construirse en cedro o abeto, con las vetas de la madera en la misma dirección que las cuerdas...</p>
		</div>
		<div id="g-ai4-10" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:47.1707%;margin-top:-9.4px;left:44.5394%;width:34px;">
			<p class="g-pstyle2">Boca</p>
		</div>
		<div id="g-ai4-11" class="g-ai2html-settings g-aiAbs" style="top:51.4086%;left:1.2229%;width:9.5833%;">
			<p>...ya que las vibraciones se transmiten mejor y con un mayor recorrido a lo largo de la veta</p>
		</div>
		<div id="g-ai4-12" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:56.4645%;margin-top:-9.4px;left:21.9349%;width:44px;">
			<p>Selleta</p>
		</div>
		<div id="g-ai4-13" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:67.4328%;margin-top:-9.4px;left:28.684%;width:46px;">
			<p class="g-pstyle2">Puente</p>
		</div>
		<div id="g-ai4-14" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:75.3869%;margin-top:-9.4px;left:56.9064%;width:14px;">
			<p class="g-pstyle1">3.</p>
		</div>
		<div id="g-ai4-15" class="g-ai2html-settings g-aiAbs" style="top:74.6011%;left:58.3541%;width:13.6667%;">
			<p>La caja de resonancia amplifica y matiza el sonido gracias al varetaje</p>
		</div>
		<div id="g-ai4-16" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:80.1593%;margin-top:-9.4px;left:0.8726%;width:42px;">
			<p>Culata</p>
		</div>
		<div id="g-ai4-17" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:89.5367%;margin-top:-9.4px;left:31.0499%;width:41px;">
			<p class="g-pstyle2">Fondo</p>
		</div>
	</div>
	<!-- End ai2html - 2023-12-31 - 00:18 -->
</div>
